var enemyListObj = {
	Highwayman: {
		tagLine: "Stand and deliver!",
		name: "Highwayman",
		maxLevel: 13,
		minLevel: 8,
		maxPossHP: 60,
		minPossHP: 45,
		maxDmg: 6,
		minDmg: 3,
		animation: "",
		maxCashDrop: 30,
		minCashDrop: 15,
		xpDrop:  20,
	},
	Goblin: {
		tagLine: "REEEEEEEEEEEE",
		name: "Goblin",
		maxLevel: 5,
		minLevel: 1,
		maxPossHP: 30,
		minPossHP: 25,
		maxDmg: 9,
		minDmg: 5,
		animation: "GoblinGif",
		legendaryAnimation: "",
		maxCashDrop: 30,
		minCashDrop: 15,
		xpDrop:  20,
	},
	Gnome: {
		tagLine: "Hello old chum!",
		name: "Gnome",
		maxLevel: 10,
		minLevel: 5,
		maxPossHP: 35,
		minPossHP: 25,
		maxDmg: 8,
		minDmg: 5,
		animation: "GnomeGif",
		legendaryAnimation: "legendaryGnomeGif",
		maxCashDrop: 30,
		minCashDrop: 15,
		xpDrop:  20
	}
};